#!/usr/bin/env python3
import requests
import yaml
import os

# List of TISS IDs to fetch
tiss_ids = [
    68412, # Jürgen Cito
    51750, # Kristof Meixner
    60223, # Michael Schröder
    306229, # Markus Böck
    340744, # Jakob Hoffmann
    48622, # Andreas Happe
    309852, # Nathanael Nussbaumer
    # add more TISS IDs here
]

OUTPUT_FILE = "_data/team/tiss_generated.yml"

# Dictionary to hold all generated entries
team_data = {}

for tiss_id in tiss_ids:
    url = f"https://tiss.tuwien.ac.at/api/person/v23/id/{tiss_id}"
    print(f"Fetching TISS ID {tiss_id}...")
    resp = requests.get(url)
    if resp.status_code != 200:
        print(f"Warning: Could not fetch TISS ID {tiss_id}")
        continue

    data = resp.json()

    # Use TISS ID as the key
    person_id = data["tiss_id"]

    # Build person entry
    person = {
        "name": f"{data.get('first_name','')} {data.get('last_name','')}".strip(),
        "role": "",
        "unit": "",
        "email": data.get("main_email", ""),
        "phone": data.get("main_phone_number", ""),
        "office": "",
        "picture": ""
    }

    # Fill employee info if available
    if data.get("employee"):
        emp = data["employee"][0]
        person["role"] = emp.get("display_function", "")
        person["unit"] = emp.get("org_ref", {}).get("name_en", "")
        person["function_group_tiss_id"] = emp.get("function_group_tiss_id", "")
        person["room_code"] = emp.get("room", {}).get("room_code", None)
        addr = emp.get("room", {}).get("address", {})
        if addr:
            person["office"] = f"{addr.get('street','')}, {addr.get('zip_code','')} {addr.get('city','')}, {addr.get('country','')}".strip(", ")

    # Picture URL
    if data.get("picture_uri"):
        person["picture"] = f"https://tiss.tuwien.ac.at{data['picture_uri']}"

    # Add to dictionary
    team_data[person_id] = person


# Ensure output directory exists
os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)

# Write YAML (overwrite each time)
with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    f.write("# This file is auto-generated by scripts/fetch_tiss.py. Do not edit manually.\n")
    for key in [tiss_id for tiss_id in tiss_ids if team_data[tiss_id]]:
        yaml.dump({key: team_data[key]}, f, allow_unicode=True)

print(f"Generated {OUTPUT_FILE} with {len(team_data)} entries.")
