#!/usr/bin/env python3
import requests
import xml.etree.ElementTree as ET
import yaml
import os

dblp_ids = [
    "150/6416",  # Jürgen Cito
]

OUTPUT_FILE = "_data/publications/dblp_generated.yml"

def text(elem, tag):
    t = elem.find(tag)
    return t.text.strip() if t is not None and t.text else ""

publications = []

for pid in dblp_ids:
    url = f"https://dblp.org/pid/{pid}.xml"
    print(f"Fetching DBLP data for {pid}...")
    resp = requests.get(url, timeout=10)
    if resp.status_code != 200:
        continue

    root = ET.fromstring(resp.text)

    for r in root.findall("r"):
        entry = list(r)[0]
        key = entry.attrib.get("key")
        if not key:
            continue

        pub = {
            "id": key,
            "title": text(entry, "title"),
            "year": int(text(entry, "year")) if text(entry, "year").isdigit() else None,
            "venue": text(entry, "journal") or text(entry, "booktitle"),
            "type": entry.tag,
            "authors": [a.text for a in entry.findall("author") if a.text],
            "url": f"https://dblp.org/rec/{key}"
        }

        publications.append(pub)

# Sort: newest first, then title
publications.sort(
    key=lambda p: (-(p["year"] or 0), p["title"])
)

os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)

with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    f.write("# This file is auto-generated by scripts/fetch_dblp.py. Do not edit manually.\n")
    yaml.dump(publications, f, allow_unicode=True)

print(f"Generated {OUTPUT_FILE} with {len(publications)} publications.")
